# Buat / timpa .env untuk deploy PC kantor (Docker Compose).
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\scripts\office\setup_env.ps1 `
#     -PostgresPassword "PtpnKantorDb2026Secure" `
#     -SecretKey "...." `
#     -SupermanUser "op_xxx" `
#     -SupermanPassword "...."

param(
    [Parameter(Mandatory = $true)]
    [string] $PostgresPassword,

    [Parameter(Mandatory = $true)]
    [string] $SecretKey,

    [string] $PostgresUser = "ptpn",
    [string] $PostgresDb = "monitoringpemasaran",
    [string] $SupermanUser = "",
    [string] $SupermanPassword = "",
    [string] $SupermanUrl = "https://superman.ptpn1.co.id/",
    [string] $SupermanExecutor = "server",
    [string] $OutFile = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path))
if (-not $OutFile) { $OutFile = Join-Path $Root ".env" }

if ($PostgresPassword.Length -lt 12) {
    throw "PostgresPassword minimal 12 karakter (disarankan 16+ alfanumerik tanpa @#:/%%)."
}
if ($SecretKey.Length -lt 24) {
    throw "SecretKey minimal 24 karakter."
}

$content = @"
# Generated by scripts/office/setup_env.ps1 — JANGAN COMMIT
POSTGRES_USER=$PostgresUser
POSTGRES_PASSWORD=$PostgresPassword
POSTGRES_DB=$PostgresDb
SECRET_KEY=$SecretKey
RUN_DB_MIGRATE=true
SUPERMAN_URL=$SupermanUrl
SUPERMAN_USER=$SupermanUser
SUPERMAN_PASSWORD=$SupermanPassword
SUPERMAN_HEADLESS=true
SUPERMAN_DEFAULT_EXECUTOR=$SupermanExecutor
"@

Set-Content -Path $OutFile -Value $content -Encoding utf8
Write-Host "Wrote $OutFile"
Write-Host "Keys: POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, SECRET_KEY, SUPERMAN_*"
